use std::collections::HashMap;
use std::env;
use std::fs::File;
use std::io::{self, BufRead, Write};
use std::process;

const LMA_SUBOP: u32 = 0b010001;
const STX_SUBOP: u32 = 0b010000;
const LDX_SUBOP: u32 = 0b011111;
const MDLX_SUBOP: u32 = 0b011110;
const MDCX_SUBOP: u32 = 0b011101;
const MDSX_SUBOP: u32 = 0b011100;

//Whether they use immediates or not and also return opcode
fn branch_info(mnemonic: &str) -> Option<(u32, bool)> {
    Some(match mnemonic {
        "BEQ"  => (0b00001, false),
        "BNE"  => (0b00010, false),
        "BGU"  => (0b00011, false),
        "BSU"  => (0b00100, false),
        "BGEU" => (0b00111, false),
        "BSEU" => (0b01000, false),
        "BGS"  => (0b00101, false),
        "BSS"  => (0b00110, false),
        "BGES" => (0b01001, false),
        "BSES" => (0b01010, false),
        "IBEQ" => (0b10001, true),
        "IBNE" => (0b10010, true),
        "IBGS" => (0b10011, true),
        "IBSS" => (0b10100, true),
        "IBGES" => (0b10101, true),
        "IBSES" => (0b10110, true),
        "IBGU" => (0b10111, true),
        "IBSU" => (0b11000, true),
        "IBGEU" => (0b11001, true),
        "IBSEU" => (0b11010, true),
        _ => return None,
    })
}

fn is_long_instr(line: &str) -> bool {
    let head = line
        .split_whitespace()
        .next()
        .unwrap_or("")
        .to_uppercase();
    head == "LMA" || head == "LDX" || head == "STX" || head == "MDLX" || head == "MDCX" || head == "MDSX" || branch_info(&head).is_some()
}

//Just one universal parse_imm function and I just use the biggests imm I could have, technically it
//is imm32 of LMA but its better to be safe
fn parse_imm64(token: &str) -> i64 {
    let clean = token.trim_start_matches('~'); //label
    //Thats easy idk what to explain
    if clean.starts_with("-0x") || clean.starts_with("-0X") {
        let hex_part = &clean[3..];
        -i64::from_str_radix(hex_part, 16).unwrap_or(0)
    } else if clean.starts_with("0x") || clean.starts_with("0X") {
        let hex_part = &clean[2..];
        i64::from_str_radix(hex_part, 16).unwrap_or(0)
    } else {
        clean.parse::<i64>().unwrap_or(0)
    }
}


//Thats just for LDX/STX and stuff
fn parse_imm64_strict(token: &str) -> i64 {
    let clean = token.trim_start_matches('~');
    let (negative, digits) = match clean.strip_prefix('-') {
        Some(rest) => (true, rest),
        None => (false, clean),
    };
    let magnitude = if digits.starts_with("0x") || digits.starts_with("0X") {
        i64::from_str_radix(&digits[2..], 16)
    } else {
        digits.parse::<i64>()
    };
    let magnitude = magnitude.unwrap_or_else(|_| {
        panic!("Assembler Error: {} is not a number nor a lable", token)
    });
    if negative { -magnitude } else { magnitude }
}

fn main() -> io::Result<()> {
    let args: Vec<String> = env::args().collect();

    if args.len() < 3 {
        eprintln!("Usage: {} <input_file.eci> <output_file.hex>", args[0]);
        process::exit(1);
    }

    let input_path = &args[1];
    let output_path = &args[2];

    let mut labels: HashMap<String, u32> = HashMap::new();
    let mut instrs: Vec<String> = Vec::new();
    let mut instr_addrs: Vec<u32> = Vec::new();
    let mut data_blocks: Vec<(u32, Vec<u8>)> = Vec::new();

    let file = File::open(input_path)?;
    let reader = io::BufReader::new(file);
    let mut address_counter: u32 = 0;

    // First pass: collect labels and instructions
    // Thats a regular two pass assembler, if you are
    // reading this ain't no way you don't know what that is
    let mut lines = reader.lines();
    while let Some(line_result) = lines.next() {
        let line = line_result?;
        let not_commented = line.split(">_").next().unwrap().trim();
        if not_commented.is_empty() {
            continue;
        }

        if not_commented.to_uppercase().starts_with("#ORG") {
            let parts: Vec<&str> = not_commented.split_whitespace().collect();
            if parts.len() > 1 {
                let target_address = parse_imm64(parts[1]) as u32;
                if target_address % 4 == 0 {
                    address_counter = target_address;
                } else {
                    panic!("Assembler Error: #ORG isn't 4 byte aligned: {}", target_address);
                }
            }
            continue;
        }
        //Alright so its a freaking .data section for a while I didn't enen look into it
        //Bc I had no idea how to implement it tbh idk why I didn't, maybe I thought it was a
        //Big change i want to reserve for later? Anyways that doesn't matter because .data
        //Is actually kinda ez, its purely software thing. So my CPU reads data from memory
        //Generated by the assembler, and if assembler would just generate the required data
        //In the required location it would just work, simple as that! For example instead of
        //LOAD rz300 <- 231
        //SPRSTR rz300 -> [GP 10]
        //Assembler can just generate 231 at that byte, and that's p much it.
        //Syntax example:
        /*
        #[ init_db 12 =>>= font_data ]#

            0x64, 0x40, 0x20, 0x15,
            0x12, 0x52, 0xaa, 0xbb,
            0xaf, 0xab, 0xda, 0xcf,

        #[ end ]#
        */
        //db is data_bytes btw not define_byte
        if not_commented.to_lowercase().starts_with("#[ init") {
            let mut init_data: Vec<i64> = Vec::new(); //For any data type

            let data_init_tokens = not_commented.trim_start_matches("#[").trim_end_matches("]#").replace("=>>=", " ");
            let parts: Vec<&str> = data_init_tokens.split_whitespace().collect();

            let elem_size: usize = match parts[0].to_lowercase().as_str() {
                "init_db" => 1, "init_dy" => 2, "init_dx" => 4, // In the name of FRs
                // (first one is db because it looks kinda nice)
                other => panic!("Assembler Error: unknown data declaration(use db, dy, dx): {}", other),
            };
            let (declared_size, data_name) = match parts.len() {
                3 => (Some(parse_imm64(parts[1]) as usize), parts[2].to_string()), //Optional size
                  //declaration is not ommitted
                2 => (None, parts[1].to_string()), //It is ommitted
                _ => panic!("Assembler Error: bad data header you are cooked buddy {}", not_commented),
            };

            //Iterate through numbers splitted by comma unil hitting end
            while let Some(l) = lines.next() {
                let l = l?;
                let body = l.split(">_").next().unwrap().trim();
                if body.is_empty() { continue; }
                if body.to_lowercase().starts_with("#[ end ]#") { break; }   // #[ end ]#
                for tok in body.split(',') {
                    let tok = tok.trim();
                    if tok.is_empty() { continue; }   // trailing comma and blank lines
                    init_data.push(parse_imm64(tok));
                }
            }
            if let Some(declared) = declared_size {
                if declared < init_data.len() {
                    panic!("Assembler Error: {} declares {} elements but has {}", data_name, declared, init_data.len());
                }
                init_data.resize(declared, 0); //That automatically pads it with 0 to fill it up to declared size
            }


            let mut data_bytes: Vec<u8> = Vec::new();
            for val in &init_data {
                for i in (0..elem_size).rev() {
                    data_bytes.push((val >> (8 * i)) as u8);
                }
            }
            while data_bytes.len() % 4 != 0 { data_bytes.push(0); } //4byte aligned to not break anything

            labels.insert(data_name, address_counter); //That label would be a base pointer to that declared data
            //strutucture, so you can do like LMA rx0 <- data_name to get a base pointer
            let start = address_counter;
            address_counter += data_bytes.len() as u32;
            data_blocks.push((start, data_bytes));
            continue
        }


        if not_commented.starts_with('~') && not_commented.ends_with(':') {
            let label = not_commented[1..not_commented.len() - 1].to_string();
            labels.insert(label, address_counter);
        } else {
            instrs.push(not_commented.to_string());
            instr_addrs.push(address_counter);
            address_counter += if is_long_instr(not_commented) { 8 } else { 4 };
        }


    }

    //Inserting all mnemonics and their opcodes into hash map
    let mut opcodes: HashMap<&str, u32> = HashMap::new();
    opcodes.insert("PAD",   0b000000);

    opcodes.insert("MOV",   0b000100);

    opcodes.insert("ADD", 0b000001);
    opcodes.insert("SUB", 0b000011);
    opcodes.insert("MUL", 0b000111);
    opcodes.insert("DIV", 0b000101);
    opcodes.insert("MOD", 0b001011);
    opcodes.insert("SDIV",0b001001);

    opcodes.insert("LOMUL", 0b000111);
    opcodes.insert("HIMUL", 0b001101);

    opcodes.insert("XOR", 0b000010);
    opcodes.insert("OR",  0b000110);
    opcodes.insert("AND", 0b001110);
    opcodes.insert("NOT", 0b001111);
    opcodes.insert("SHL", 0b001000);
    opcodes.insert("SHR", 0b001100);
    opcodes.insert("SRA", 0b001010);

    opcodes.insert("RNG", 0b111100);

    opcodes.insert("LOAD", 0b010001);
    opcodes.insert("LMA", 0b000000);
    opcodes.insert("LDR", 0b100011);
    opcodes.insert("STR", 0b100111);
    opcodes.insert("LDX", 0b000000);
    opcodes.insert("MDLX", 0b000000);
    opcodes.insert("MDCX", 0b000000);
    opcodes.insert("MDSX", 0b000000);
    opcodes.insert("STX", 0b000000);

    //Escape for branches
    for name in ["BEQ", "BNE", "BGU", "BSU", "BGEU", "BSEU", "BGS", "BSS", "BGES", "BSES",
                 "IBEQ", "IBNE", "IBGS", "IBSS", "IBGES", "IBSES",
                 "IBGU", "IBSU", "IBGEU", "IBSEU"] {
        opcodes.insert(name, 0b110000);
    }

    opcodes.insert("JMP", 0b111111);
    opcodes.insert("JR", 0b110111);
    opcodes.insert("CALL", 0b111000);
    opcodes.insert("RET", 0b010000);
    opcodes.insert("SYS", 0b010010);
    opcodes.insert("RETU", 0b111101);

    opcodes.insert("SPRLDR", 0b101000);
    opcodes.insert("SPRSTR", 0b101001);
    opcodes.insert("SPRSET", 0b101010);
    opcodes.insert("SPRADD", 0b101011);
    opcodes.insert("SPRSUB", 0b101100);
    opcodes.insert("SPRLEA", 0b101101);
    opcodes.insert("PUSH",  0b100100);
    opcodes.insert("POP",   0b100101);

    let mut output_file = File::create(output_path)?;

    let mut image: Vec<u8> = Vec::new();
    let mut used: Vec<bool> = Vec::new();

    // Second pass: Instruction construction cool rhyme
    for (current_address, inst_line) in instrs.iter().enumerate() {
        let current_pc = instr_addrs[current_address];

        //As you might have guessed I absolutely love fira code ligatures
        //If you look at my project without fira code, well I consider
        //It a crime
        let cleared = inst_line
            .replace("<-", " ")
            .replace("[", " ")
            .replace("]", " ")
            .replace(",", " ")
            .replace("->", " ")
            .replace(">", " ")
            .replace("<", " ")
            .replace("=", " ")
            .replace("+", " ");

        let tokens: Vec<&str> = cleared.split_whitespace().collect();

        if tokens.is_empty() {
            continue;
        }

        let mut instr = tokens[0].to_uppercase();
        let mut tokens = tokens;

        // Its encoding stuff just look at CORE i don't feel like explaning
        if let Some((canonical, sel_name)) = expand_spr_sugar(&instr) {
            instr = canonical.to_string();
            tokens.insert(2, sel_name);
        }
        let opcode = *opcodes.get(instr.as_str()).unwrap_or_else(|| {
            panic!("Unknown instruction token: {}", instr);
        });

        let mut rx0: u32 = 0;
        let mut rx1: u32 = 0;
        let mut index_reg: u32 = 0;
        let mut scale: u32 = 0;
        let mut immediate: i64 = 0;
        let mut branch_target: i64 = 0;
        let mut word1: Option<u32> = None;
        let mut mdx_stride: i64 = 0;
        let mut mdx_dest: u32 = 0;

        //Thats a bigass match case but yeah there is nothing hard its just literally pattern matching
        //To the ISA, like its also pretty self explanotory
        match instr.as_str() {
            "LOAD" => {
                if tokens.len() > 1 {
                    rx0 = parse_reg(tokens[1]);
                }
                if tokens.len() > 2 {
                    immediate = parse_imm64(tokens[2]);
                }
            }
            "LMA" => {
                if tokens.len() > 1 {
                    rx0 = parse_reg(tokens[1]);
                }
                if tokens.len() > 2 {
                    immediate = resolve_sum(&tokens[2..], &labels);
                }
            }
            //If yk ISA you should have to questions
            "MDLX" | "MDCX" | "MDSX" => {
                let mut ops: Vec<String> = Vec::new();
                let mut negate = false;
                for t in tokens[1..].iter() {
                    if *t == "*" { continue; }
                    if *t == "-" { negate = true; continue; }
                    ops.push(if negate { format!("-{}", t) } else { t.to_string() });
                    negate = false;
                }
                if ops.len() < 6 {
                    panic!("Assembler Error: {} needs dest, base, index, stride, shift reg and scale, got {:?}", instr, ops);
                }
                let full = |name: &str, what: &str| -> u32 {
                    let sel = parse_reg(name);
                    if sel & 0b111 != 0 {
                        panic!("Assembler Error: {} {} '{}' must be a full rx register", instr, what, name);
                    }
                    sel >> 3
                };
                mdx_dest   = parse_reg(&ops[0]);
                rx1        = full(&ops[1], "base");
                index_reg  = full(&ops[2], "index");
                mdx_stride = parse_imm64(&ops[3]);
                rx0        = full(&ops[4], "shift register");
                scale      = parse_imm64(&ops[5]) as u32;
                immediate  = ops[6..].iter().map(|o| resolve_abs(o, &labels)).sum();
                if !(-8192..=8191).contains(&mdx_stride) {
                    panic!("Assembler Error: {} stride {} does not fit in signed 14 bits", instr, mdx_stride);
                }
                if scale > 3 {
                    panic!("Assembler Error: {} shift {} must be 0..3", instr, scale);
                }
                if !(-4096..=4095).contains(&immediate) {
                    panic!("Assembler Error: {} offset {} does not fit in signed imm13, put the address in the base register with LMA instead", instr, immediate);
                }
            }
            "LDX" | "STX" => {
                if tokens.len() < 5 {
                    panic!("Assembler Error: {} needs value, base, index and shift, got {:?}", instr, &tokens[1..]);
                }
                rx0 = parse_reg(tokens[1]);
                let base_sel = parse_reg(tokens[2]);
                if base_sel & 0b111 != 0 {
                    panic!("Assembler Error: {} base '{}' must be a full rx register", instr, tokens[2]);
                }
                rx1 = base_sel >> 3;
                index_reg = parse_reg(tokens[3]);
                scale = parse_imm64(tokens[4]) as u32;
                if scale > 3 {
                    panic!("Assembler Error: {} shift {} must be 0..3", instr, scale);
                }
                immediate = if tokens.len() > 5 {
                    resolve_sum(&tokens[5..], &labels)
                } else {
                    0
                };
                if !(-268435456..=268435455).contains(&immediate) {
                    panic!("Assembler Error: {} offset {} does not fit in signed imm29", instr, immediate);
                }
            }
            "LDR" | "STR" => {
                if tokens.len() > 1 {
                    rx0 = parse_reg(tokens[1]);
                }
                if tokens.len() > 2 {
                    rx1 = parse_reg(tokens[2]);
                }
                if tokens.len() > 3 {
                    if tokens[3] == "-" && tokens.len() > 4 {
                        let val = parse_imm64(tokens[4]);
                        immediate = -val;
                    } else if tokens[3] == "+" && tokens.len() > 4 {
                        immediate = parse_imm64(tokens[3]);
                    } else {
                        let target = tokens[3].trim_start_matches('~');
                        if let Some(&label_addr) = labels.get(target) {
                            let offset = (label_addr as i64) - ((current_pc + 4) as i64);
                            immediate = offset;
                        } else {
                            immediate = parse_imm64(tokens[3]);
                        }
                    }
                }
            }
            "ADD" | "SUB" | "MUL" | "LOMUL" | "DIV" | "MOD" | "SDIV" => {
                let mut dest_reg: u32 = 0;
                let mut src1_reg: u32 = 0;
                let src2_reg: u32;
                let mut stride_bits: u32 = 0b00;

                if tokens.len() > 1 { dest_reg = parse_reg(tokens[1]); }
                if tokens.len() > 2 { src1_reg = parse_reg(tokens[2]); }
                if tokens.len() > 3 { src2_reg = parse_reg(tokens[3]); } else {
                    src2_reg = src1_reg;
                    src1_reg = dest_reg;
                }

                // Handle both "- 1" (tokens[4] == "-", tokens[5] == "1") 
                // and "-1" / "+1" (tokens[4] == "-1")
                if tokens.len() > 4 {
                    let stride_val = if tokens[4] == "-" && tokens.len() > 5 {
                        -parse_imm64(tokens[5])
                    } else if tokens[4] == "+" && tokens.len() > 5 {
                        parse_imm64(tokens[5])
                    } else {
                        parse_imm64(tokens[4])
                    };

                    stride_bits = match stride_val {
                        1 => 0b01,  // +1
                        2 => 0b10,  // +2
                        -1 => 0b11, // -1 (Encodes to 0b11 for custom_imm2)
                        _ => 0b00,
                    };
                }

                rx0 = src1_reg;
                rx1 = src2_reg;
                immediate = (((dest_reg & 0xFF) as i64) << 2) | (stride_bits as i64);
            }
            //How did I not noticed the CMP here? Well whatever ill let it be as a sort of remenance
            "CMP" => {
                if tokens.len() > 1 {
                    rx0 = parse_reg(tokens[1]);
                }
                if tokens.len() > 2 {
                    rx1 = parse_reg(tokens[2]);
                }
                if tokens.len() > 3 {
                    if tokens[3] == "-" && tokens.len() > 4 {
                        let val = parse_imm64(tokens[4]);
                        immediate = -val;
                    } else if tokens[3] == "+" && tokens.len() > 4 {
                        immediate = parse_imm64(tokens[3]);
                    } else {
                        let target = tokens[3].trim_start_matches('~');
                        if let Some(&label_addr) = labels.get(target) {
                            let offset = (label_addr as i64) - ((current_pc + 4) as i64);
                            immediate = offset;
                        } else {
                            immediate = parse_imm64(tokens[3]);
                        }
                    }
                }
            }
            m if branch_info(m).is_some() => {
                let (_, uses_imm) = branch_info(m).unwrap();
                if tokens.len() < 4 {
                    panic!("Assembler Error: {} needs 3 operands, got {:?}", instr, &tokens[1..]);
                }
                rx0 = parse_reg(tokens[1]);
                if uses_imm {
                    immediate = parse_imm64(tokens[2]);
                    if !(-262144..=262143).contains(&immediate) {
                        panic!("Assembler Error: {} literal {} does not fit in signed imm19", instr, immediate);
                    }
                } else {
                    rx1 = parse_reg(tokens[2]);
                }
                let target = tokens[3].trim_start_matches('~');
                branch_target = if let Some(&label_addr) = labels.get(target) {
                    label_addr as i64
                } else {
                    parse_imm64(tokens[3])
                };
                if branch_target & 0x3 != 0 {
                    panic!("Assembler Error: {} target {:#X} is not 4-byte aligned", instr, branch_target);
                }
                if branch_target < 0 || branch_target >= (1 << 28) {
                    panic!("Assembler Error: {} target {:#X} is outside the 256MB range", instr, branch_target);
                }
            }
            "JR" => {
                if tokens.len() > 1 {
                    rx0 = parse_reg(tokens[1]);
                }
            }
            "JMP" | "CALL" => {
                if tokens.len() > 1 {
                    let target = tokens[1].trim_start_matches('~');
                    let absolute = if let Some(&label_addr) = labels.get(target) {
                        label_addr as i64
                    } else {
                        parse_imm64(tokens[1])
                    };
                    if absolute & 0x3 != 0 {
                        panic!("Assembler Error: {} target {:#X} is not 4-byte aligned", instr, absolute);
                    }
                    if absolute < 0 || absolute >= (1 << 28) {
                        panic!("Assembler Error: {} target {:#X} is outside the 256MB range", instr, absolute);
                    }
                    immediate = absolute >> 2;
                }
            }
            "SPRLDR" | "SPRSTR" | "SPRSET" | "SPRADD" | "SPRSUB" | "SPRLEA" => {
                if tokens.len() > 1 { rx0 = parse_reg(tokens[1]); }
                if tokens.len() > 2 { rx1 = parse_spr(tokens[2]); }
                if tokens.len() > 3 {
                    if tokens[3] == "-" && tokens.len() > 4 {
                        immediate = -parse_imm64(tokens[4]);
                    } else if tokens[3] == "+" && tokens.len() > 4 {
                        immediate = parse_imm64(tokens[4]);
                    } else {
                        immediate = parse_imm64(tokens[3]);
                    }
                }
            }
            "PUSH" | "POP" | "RNG" => {
                if tokens.len() > 1 { rx0 = parse_reg(tokens[1]); }
            }
            "RET" | "SYS" | "RETU" | "PAD" => {}
            _ => {
                if tokens.len() > 1 {
                    rx0 = parse_reg(tokens[1]);
                }
                if tokens.len() > 2 {
                    rx1 = parse_reg(tokens[2]);
                }
                if tokens.len() > 3 {
                    if tokens[3] == "-" && tokens.len() > 4 {
                        let val = parse_imm64(tokens[4]);
                        immediate = -val;
                    } else if tokens[3] == "+" && tokens.len() > 4 {
                        immediate = parse_imm64(tokens[3]);
                    } else {
                        let target = tokens[3].trim_start_matches('~');
                        if let Some(&label_addr) = labels.get(target) {
                            let offset = (label_addr as i64) - ((current_pc + 4) as i64);
                            immediate = offset;
                        } else {
                            immediate = parse_imm64(tokens[3]);
                        }
                    }
                }
            }
        }

        let imm_u32 = immediate as u32;

        //Now that is a somewhate scary part but again its just converting instructions to actual bits
        //Nothing too hard just kinda tedius
        let machine_code: u32 = match instr.as_str() {
            "JMP" | "CALL" => {
                ((opcode & 0x3F) << 26) | (imm_u32 & 0x03FF_FFFF)
            }
            m if branch_info(m).is_some() => {
                let (bop, uses_imm) = branch_info(m).unwrap();
                let i = imm_u32 & 0x0007_FFFF;
                let hi  = if uses_imm { (i >> 11) & 0xFF } else { rx1 & 0xFF };
                let mid = if uses_imm { (i >> 6) & 0x1F } else { 0 };
                let lo  = if uses_imm { i & 0x3F } else { 0 };
                word1 = Some((lo << 26) | (((branch_target as u32) >> 2) & 0x03FF_FFFF));
                ((opcode & 0x3F) << 26)
                    | ((rx0 & 0xFF) << 18)
                    | (hi << 10)
                    | ((bop & 0x1F) << 5)
                    | mid
            }
            "SPRLDR" | "SPRSTR" | "SPRSET" | "SPRADD" | "SPRSUB" | "SPRLEA" => {
                ((opcode & 0x3F) << 26)
                    | ((rx0 & 0xFF) << 18)
                    | ((rx1 & 0b11) << 16)
                    | ((immediate as u32) & 0xFFFF)
            }
            "LOAD" => {
                ((opcode & 0x3F) << 26)
                    | ((rx0 & 0xFF) << 18)
                    | ((immediate as u32) & 0x0003_FFFF)
            }
            "LDX" | "STX" => {
                let subop = if instr == "LDX" { LDX_SUBOP } else { STX_SUBOP };
                let i = imm_u32 & 0x1FFF_FFFF;
                word1 = Some(((index_reg & 0xFF) << 24) | ((scale & 0x3) << 22) | (i & 0x003F_FFFF));
                ((opcode & 0x3F) << 26)
                    | ((rx0 & 0xFF) << 18)
                    | ((rx1 & 0x1F) << 13)
                    | (((i >> 26) & 0x7) << 10)
                    | ((subop & 0x3F) << 4)
                    | ((i >> 22) & 0xF)
            }
            "MDLX" | "MDCX" | "MDSX" => {
                let subop = match instr.as_str() { "MDLX" => MDLX_SUBOP, "MDCX" => MDCX_SUBOP, _ => MDSX_SUBOP };
                let st = (mdx_stride as u32) & 0x3FFF;
                word1 = Some(((index_reg & 0x1F) << 27)
                    | ((mdx_dest & 0xFF) << 19)
                    | ((scale & 0x3) << 17)
                    | ((st & 0xF) << 13)
                    | (imm_u32 & 0x1FFF));
                ((opcode & 0x3F) << 26)
                    | ((rx0 & 0x1F) << 21)
                    | (((st >> 11) & 0x7) << 18)
                    | ((rx1 & 0x1F) << 13)
                    | (((st >> 8) & 0x7) << 10)
                    | ((subop & 0x3F) << 4)
                    | ((st >> 4) & 0xF)
            }
            "LMA" => {
                word1 = Some(imm_u32);
                ((opcode & 0x3F) << 26)
                    | ((rx0 & 0xFF) << 18)
                    | ((LMA_SUBOP & 0x3F) << 4)
            }
            _ => {
                ((opcode & 0x3F) << 26)
                    | ((rx0 & 0xFF) << 18)
                    | ((rx1 & 0xFF) << 10)
                    | (imm_u32 & 0x03FF)
            }
        };

        //Big endian btw
        place_in_mem(&mut image, &mut used, current_pc, &machine_code.to_be_bytes());
        if let Some(w1) = word1 {
            place_in_mem(&mut image, &mut used, current_pc + 4, &w1.to_be_bytes());
        }
    }
    for (addr, bytes) in &data_blocks {
        place_in_mem(&mut image, &mut used, *addr, bytes);
    }
    for block in &image {
        writeln!(output_file, "{:02X}", block)?;
    }

    Ok(())
}

//Well parsing regs what more can I say
fn parse_reg(reg_str: &str) -> u32 {
    let upper = reg_str.to_uppercase();

    let prefix = if upper.starts_with("RZ") {
        "RZ"
    } else if upper.starts_with("RY") {
        "RY"
    } else if upper.starts_with("RX") {
        "RX"
    } else if upper.starts_with('R') {
        "R"
    } else {
        panic!("Assembler Error: invalid register '{}'", reg_str);
    };

    let rest = upper.trim_start_matches(prefix);

    if rest.contains('_') || rest.contains('.') {
        let parts: Vec<&str> = rest.split(|c| c == '_' || c == '.').collect();
        let reg_id = parts[0].parse::<u32>().unwrap_or(0) & 0x1F;
        let sub_offset = parts.get(1).and_then(|s| s.parse::<u32>().ok()).unwrap_or(0) & 0x07;
        return (reg_id << 3) | sub_offset;
    }

    let num = rest.parse::<u32>().unwrap_or(0);

    match prefix {
        "RZ" => {
            let reg_id = (num / 10) & 0x1F;
            let byte_sel = (num % 10) & 0x03;
            let offset = 0b011 + byte_sel;
            (reg_id << 3) | offset
        }
        "RY" => {
            let reg_id = (num / 10) & 0x1F;
            let half_sel = (num % 10) & 0x01;
            let offset = 0b001 + half_sel;
            (reg_id << 3) | offset
        }
        _ => {
            let reg_id = num & 0x1F;
            (reg_id << 3) | 0b000
        }
    }
}

//ORG overlaps with code or other data
fn place_in_mem(image: &mut Vec<u8>, used: &mut Vec<bool>, addr: u32, bytes: &[u8]) {
    let start = addr as usize;
    let end = start + bytes.len();
    if image.len() < end { image.resize(end, 0); used.resize(end, false); }
    for (i, b) in bytes.iter().enumerate() {
        if used[start + i] { panic!("Assembler Error: overlap at 0x{:X}", start + i); }
        image[start + i] = *b;
        used[start + i] = true;
    }
}

fn parse_spr(name: &str) -> u32 {
    match name.to_uppercase().as_str() {
        "SP" => 0b00,
        "LR" => 0b01,
        "GP" => 0b10,
        other => panic!("Assembler Error: unknown SPR '{}'", other),
    }
}

//So we can basically do this LDX rx0 <=< [rx31, rx5 << 2 + *font_data]
//Which is so sick
fn resolve_abs(token: &str, labels: &HashMap<String, u32>) -> i64 {
    let name = token.trim_start_matches(['~', '*']);
    match labels.get(name) {
        Some(&addr) => addr as i64,
        None => parse_imm64_strict(token),
    }
}

//For label + imm(29th bit of LDX/STX its just perfect)
fn resolve_sum(tokens: &[&str], labels: &HashMap<String, u32>) -> i64 {
    let mut total: i64 = 0;
    let mut negate = false;
    for token in tokens {
        if *token == "-" {
            negate = true;
            continue;
        }
        let value = resolve_abs(token, labels);
        total += if negate { -value } else { value };
        negate = false;
    }
    total
}

fn expand_spr_sugar(instr: &str) -> Option<(&'static str, &'static str)> {
    let (suffix, sel_name) = if let Some(rest) = instr.strip_prefix("SP") {
        (rest, "SP")
    } else if let Some(rest) = instr.strip_prefix("LR") {
        (rest, "LR")
    } else if let Some(rest) = instr.strip_prefix("GP") {
        (rest, "GP")
    } else {
        return None;
    };

    let canonical = match suffix {
        "SET" => "SPRSET",
        "ADD" => "SPRADD",
        "SUB" => "SPRSUB",
        "LDR" => "SPRLDR",
        "STR" => "SPRSTR",
        "LEA" => "SPRLEA",
        _ => return None,
    };

    Some((canonical, sel_name))
}
