mod IR3AC;
mod codegen;
mod generate;
mod lexer;
mod parser;
mod semantic;
mod viz;

use IR3AC::IR;
use codegen::{Codegen, GlobalLayout};
use generate::generate_assembly;
use lexer::Lexer;
use parser::Parser;
use semantic::Semantic;

use std::collections::HashMap;
use std::fs;
use clap::Parser as ClapParser;
use std::path::PathBuf;

#[derive(ClapParser, Debug)]
#[command(author = "Qclipsing", version = "v0.0", about = "Flare-10k Compiler", long_about = None)]
struct Args {
    //What he hell is clap doing?

    ///Path to the input file
    #[arg(value_name = "FILE")]
    input: PathBuf,

    ///Path to the output file(default: <input file>.eci)
    #[arg(short = 'o', long, value_name = "FILE")]
    output: Option<PathBuf>,

    ///Output tokens generated by lexer and halt
    #[arg(long)]
    lex: bool,

    ///Output AST generated by parser and halt
    #[arg(long)]
    ast: bool,

    ///Output IR generated by well IR and halt
    #[arg(long)]
    ir: bool,

    ///Output assembly
    #[arg(long)]
    asm: bool,

    ///Generate a visualization of interference graph generated by the codegen
    #[arg(long)]
    graph: bool,
}

fn main() {
    let args = Args::parse();
    // Read Source File
    let src = fs::read_to_string(&args.input).unwrap_or_else(|err| {
        eprintln!("Error: Could not read file {:?}: {}", args.input, err);
        std::process::exit(1);
    });
    let lexer = Lexer::new(&src, 1, 1);
    if args.lex {
        println!("Lexer:");
        println!("{:?}", lexer);
        return;
    }
    let mut parser = Parser::new(lexer);
    let ast = parser.parse_everything();
    if args.ast {
        println!("Parser's AST:");
        println!("{:#?}", ast);
        return;
    }
    let mut semantic_analyzer = Semantic::new(&ast);
    semantic_analyzer.check_program(&ast);
    let mut ir_generator = IR::new(&ast);
    let ir_program = ir_generator.reduce_everything(&ast);
    if args.ir {
        println!("IR:");
        println!("{:#?}", ir_program);
        return;
    }
    let mut ast_structs = HashMap::new();
    for s in &ast.structs {
        ast_structs.insert(s.name.clone(), s.clone());
    }
    let global_layout = GlobalLayout::build(&ir_program.globals, &ast_structs);
    let mut all_instructions = Vec::new();
    let mut function_graphs: Vec<viz::FunctionGraph> = Vec::new();

    let mut top_level_iter = ir_program.top_level.iter();
    let mut leading_inline: Option<&Vec<String>> = None;
    if let Some(IR3AC::TopLevelIR::InlineAsm(lines)) = ir_program.top_level.first() {
        leading_inline = Some(lines);
        top_level_iter.next();
    }

    all_instructions.extend(Codegen::emit_global_preamble(&global_layout));
    for item in top_level_iter {
        match item {
            IR3AC::TopLevelIR::Global(name) => {
                all_instructions.extend(Codegen::emit_single_global_init(name, &global_layout));
            }
            IR3AC::TopLevelIR::Function(name) => {
                let ir_func = ir_program
                    .functions
                    .iter()
                    .find(|f| &f.name == name)
                    .expect("Codegen error: unknown function in top-level order");
                let mut cg = Codegen::new(ir_func, &ast_structs, &global_layout);
                cg.run_allocator();
                if args.graph {
                    if let Some(fg) = cg.extract_coloring_graph() {
                        function_graphs.push(fg);
                    }
                }
                all_instructions.extend(cg.lower_func());
            }
            IR3AC::TopLevelIR::InlineAsm(lines) => {
                for line in lines {
                    all_instructions.push(codegen::AsmInst::Inline(line.clone()));
                }
            }
        }
    }
    if args.graph {
        viz::render_svg(&function_graphs, "color_graph.svg");
        println!("Coloring graph written to: \"color_graph.svg\"");
    }
    let mut asm_text = generate_assembly(all_instructions).expect("Codegen error: failed to compile");
    if let Some(lines) = leading_inline {
        let mut prefix = String::new();
        for line in lines {
            if !line.starts_with(['~', '#']) {
                prefix.push('\t');
            }
            prefix.push_str(line);
            prefix.push('\n');
        }
        asm_text = prefix + &asm_text;
    }
    if args.asm {
        println!("Assembly:");
        println!("{}", asm_text);
        return;
    }
    let output_path = args
        .output
        .clone()
        .unwrap_or_else(|| args.input.with_extension("s"));
    fs::write(&output_path, &asm_text).unwrap_or_else(|err| {
        eprintln!("Error: Could not write file {:?}: {}", output_path, err);
        std::process::exit(1);
    });
    println!(
        "Compilation succeeded! Assembly written to: {:?}",
        output_path
    );
}
