//Visualizer of the coloring algorithm
//Alright so yes this file was indeed generated by AI, but man do I not want to write visualizer.
//And its just not the scope of that project, its just a fun visualizer nothing else.




use crate::IR3AC::{IRInst, IROperand};
use std::collections::BTreeMap;

//Temps are written exactly once, every id comes off a fresh counter, so the instruction that
//defines one *is* its value and is safe to print next to the name
//Everything but a constant keeps its node label verbatim so you can trace it back to a pill,
//constants never make it into the graph so they may as well print as the plain number
fn op_text(op: &IROperand) -> String {
    match op {
        IROperand::SignedConstant(value) => value.to_string(),
        IROperand::UnsignedConstant(value) => value.to_string(),
        other => format!("{:?}", other),
    }
}

pub fn describe_def(inst: &IRInst) -> Option<String> {
    let binary = |symbol: &str, left: &IROperand, right: &IROperand| {
        Some(format!("= {} {} {}", op_text(left), symbol, op_text(right)))
    };
    match inst {
        IRInst::Add { left, right, .. } => binary("+", left, right),
        IRInst::Sub { left, right, .. } => binary("-", left, right),
        IRInst::Mul { left, right, .. } => binary("*", left, right),
        IRInst::Div { left, right, .. } => binary("/", left, right),
        IRInst::Mod { left, right, .. } => binary("%", left, right),
        IRInst::Shl { left, right, .. } => binary("<<", left, right),
        IRInst::Shr { left, right, .. } => binary(">>", left, right),
        IRInst::Xor { left, right, .. } => binary("^", left, right),
        IRInst::Or { left, right, .. } => binary("|", left, right),
        IRInst::And { left, right, .. } => binary("&", left, right),
        IRInst::Not { src, .. } => Some(format!("= ~{}", op_text(src))),
        IRInst::Negate { src, .. } => Some(format!("= -{}", op_text(src))),
        IRInst::Cpy { src, .. } => Some(format!("= {}", op_text(src))),
        IRInst::Cast {
            src, target_type, ..
        } => Some(format!("= ({:?}) {}", target_type, op_text(src))),
        IRInst::LoadPtr { ptr_addr, .. } => Some(format!("= [{}]", op_text(ptr_addr))),
        IRInst::RegFieldRead {
            struct_var,
            byte_offset,
            byte_size,
            ..
        } => Some(format!(
            "= {}@{}:{}",
            op_text(struct_var),
            byte_offset,
            byte_size
        )),
        IRInst::Call { name, .. } => Some(format!("= {}()", name)),
        IRInst::LocalAddr { offset, .. } => Some(format!("= &local+{}", offset)),
        IRInst::GlobalAddr { offset, .. } => Some(format!("= &global+{}", offset)),
        _ => None,
    }
}

pub enum Slot {
    Register {
        name: String,
        base: u8,
        byte_lo: u8,
        bytes: u8,
    },
    Spilled,
    Unassigned,
}

pub struct GraphNode {
    pub label: String,
    pub detail: Option<String>,
    pub slot: Slot,
}

pub struct FunctionGraph {
    pub name: String,
    pub nodes: Vec<GraphNode>,
    pub edges: Vec<(usize, usize)>,
}

fn hsl_to_rgb(h: f64, s: f64, l: f64) -> (u8, u8, u8) {
    if s == 0.0 {
        let v = (l * 255.0).round() as u8;
        return (v, v, v);
    }
    let q = if l < 0.5 { l * (1.0 + s) } else { l + s - l * s };
    let p = 2.0 * l - q;
    let hue_to_rgb = |p: f64, q: f64, t: f64| -> f64 {
        let mut t = t;
        if t < 0.0 {
            t += 1.0;
        }
        if t > 1.0 {
            t -= 1.0;
        }
        if t < 1.0 / 6.0 {
            return p + (q - p) * 6.0 * t;
        }
        if t < 1.0 / 2.0 {
            return q;
        }
        if t < 2.0 / 3.0 {
            return p + (q - p) * (2.0 / 3.0 - t) * 6.0;
        }
        p
    };
    let r = hue_to_rgb(p, q, h + 1.0 / 3.0);
    let g = hue_to_rgb(p, q, h);
    let b = hue_to_rgb(p, q, h - 1.0 / 3.0);
    (
        (r * 255.0).round() as u8,
        (g * 255.0).round() as u8,
        (b * 255.0).round() as u8,
    )
}

fn hex(rgb: (u8, u8, u8)) -> String {
    format!("#{:02x}{:02x}{:02x}", rgb.0, rgb.1, rgb.2)
}

//Bit reversing the id spreads the 32 registers evenly around the wheel, plain id*137 collides
//(r3 lands on 51 degrees, r24 on 48) which made two different registers look like one colour
//Neighbours on that wheel are only 11 degrees apart, so every other one is muted to pull them apart
fn base_spread(base: u8) -> (f64, f64) {
    let id = base & 31;
    let mut rev = 0u8;
    for bit in 0..5 {
        if id & (1 << bit) != 0 {
            rev |= 1 << (4 - bit);
        }
    }
    let sat_scale = if rev % 2 == 0 { 1.0 } else { 0.72 };
    (rev as f64 / 32.0, sat_scale)
}

//Hue comes from the base register, fragments of the same register share it and split on lightness
fn slot_hsl(slot: &Slot) -> (f64, f64, f64) {
    match slot {
        Slot::Register {
            base,
            byte_lo,
            bytes,
            ..
        } => {
            let (hue, sat) = base_spread(*base);
            match bytes {
                4 => (hue, 0.62 * sat, 0.58),
                2 => (hue, 0.70 * sat, if *byte_lo == 0 { 0.46 } else { 0.76 }),
                _ => (hue, 0.78 * sat, 0.28 + 0.13 * (*byte_lo as f64)),
            }
        }
        Slot::Spilled => (0.0, 0.0, 0.62),
        Slot::Unassigned => (0.0, 0.0, 0.86),
    }
}

fn fill_of(slot: &Slot) -> String {
    let (h, s, l) = slot_hsl(slot);
    hex(hsl_to_rgb(h, s, l))
}

fn stroke_of(slot: &Slot) -> String {
    let (h, s, l) = slot_hsl(slot);
    hex(hsl_to_rgb(h, s, (l * 0.55).max(0.05)))
}

fn ink_of(slot: &Slot) -> &'static str {
    let (_, _, l) = slot_hsl(slot);
    if l > 0.55 { "#101010" } else { "#ffffff" }
}

//Sorts registers first (by id, then by which bytes they own), then spills, then whatever got nothing
fn legend_key(slot: &Slot) -> (u8, u8, u8, u8) {
    match slot {
        Slot::Register {
            base,
            byte_lo,
            bytes,
            ..
        } => (0, *base, *byte_lo, *bytes),
        Slot::Spilled => (1, 0, 0, 0),
        Slot::Unassigned => (2, 0, 0, 0),
    }
}

fn legend_text(slot: &Slot) -> String {
    match slot {
        Slot::Register { name, .. } => name.clone(),
        Slot::Spilled => "spilled".to_string(),
        Slot::Unassigned => "unassigned".to_string(),
    }
}

fn escape_xml_text(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

const FONT: &str = "ui-monospace,SFMono-Regular,Menlo,Consolas,monospace";
const LABEL_SIZE: f64 = 9.0;
const CHAR_W: f64 = LABEL_SIZE * 0.6;
const DETAIL_SIZE: f64 = 8.0;
const NODE_H: f64 = 21.0;
const DETAIL_H: f64 = 13.0;
const PAD: f64 = 34.0;
const TITLE_H: f64 = 34.0;
const LEGEND_W: f64 = 170.0;
const LEGEND_ROW: f64 = 21.0;

//Fruchterman-Reingold, deterministic seeding so the same program always draws the same picture
fn force_layout(sizes: &[(f64, f64)], edges: &[(usize, usize)]) -> Vec<(f64, f64)> {
    let n = sizes.len();
    let mut pos = vec![(0.0_f64, 0.0_f64); n];
    if n == 0 {
        return pos;
    }

    let avg = sizes.iter().map(|s| (s.0 + s.1) * 0.5).sum::<f64>() / n as f64;
    let k = (avg * 1.9).max(52.0);

    //Sunflower spiral, spreads the seed evenly instead of relying on a rng
    for i in 0..n {
        let angle = i as f64 * 2.399963229728653;
        let r = ((i as f64) + 0.5).sqrt() * k * 0.95;
        pos[i] = (r * angle.cos(), r * angle.sin());
    }
    if n == 1 {
        return pos;
    }

    let iters: usize = if n > 300 { 250 } else { 600 };
    let mut temp = k * 2.0;
    let cool = 0.01_f64.powf(1.0 / iters as f64);
    let gravity = (2.0 / n as f64).clamp(0.02, 0.5);

    let mut disp = vec![(0.0_f64, 0.0_f64); n];
    for _ in 0..iters {
        for d in disp.iter_mut() {
            *d = (0.0, 0.0);
        }

        for i in 0..n {
            for j in (i + 1)..n {
                let mut dx = pos[i].0 - pos[j].0;
                let mut dy = pos[i].1 - pos[j].1;
                if dx * dx + dy * dy < 1e-6 {
                    dx = ((i * 7 + j * 13) % 17) as f64 * 0.05 - 0.4;
                    dy = ((i * 11 + j * 5) % 19) as f64 * 0.05 - 0.45;
                }
                let d = (dx * dx + dy * dy).sqrt();
                let f = k * k / d;
                let (ux, uy) = (dx / d * f, dy / d * f);
                disp[i].0 += ux;
                disp[i].1 += uy;
                disp[j].0 -= ux;
                disp[j].1 -= uy;
            }
        }

        for &(a, b) in edges {
            let dx = pos[a].0 - pos[b].0;
            let dy = pos[a].1 - pos[b].1;
            let d = (dx * dx + dy * dy).sqrt().max(0.01);
            let f = d * d / k;
            let (ux, uy) = (dx / d * f, dy / d * f);
            disp[a].0 -= ux;
            disp[a].1 -= uy;
            disp[b].0 += ux;
            disp[b].1 += uy;
        }

        //Repulsion alone sends edgeless nodes to infinity, this reels them back in
        for i in 0..n {
            disp[i].0 -= pos[i].0 * gravity;
            disp[i].1 -= pos[i].1 * gravity;
        }

        for i in 0..n {
            let len = (disp[i].0 * disp[i].0 + disp[i].1 * disp[i].1).sqrt();
            if len < 1e-9 {
                continue;
            }
            let step = len.min(temp);
            pos[i].0 += disp[i].0 / len * step;
            pos[i].1 += disp[i].1 / len * step;
        }
        temp *= cool;
    }

    //The forces treat nodes as points, so pull apart whatever still overlaps as boxes
    for _ in 0..120 {
        let mut moved = false;
        for i in 0..n {
            for j in (i + 1)..n {
                let dx = pos[j].0 - pos[i].0;
                let dy = pos[j].1 - pos[i].1;
                let ox = (sizes[i].0 + sizes[j].0) * 0.5 + 10.0 - dx.abs();
                let oy = (sizes[i].1 + sizes[j].1) * 0.5 + 10.0 - dy.abs();
                if ox <= 0.0 || oy <= 0.0 {
                    continue;
                }
                moved = true;
                if ox < oy {
                    let s = if dx < 0.0 { -ox } else { ox } * 0.5;
                    pos[i].0 -= s;
                    pos[j].0 += s;
                } else {
                    let s = if dy < 0.0 { -oy } else { oy } * 0.5;
                    pos[i].1 -= s;
                    pos[j].1 += s;
                }
            }
        }
        if !moved {
            break;
        }
    }

    pos
}

//Disconnected pieces would otherwise drift to the gravity/repulsion ring and blow up the canvas,
//so each component is laid out on its own and the results are shelf packed
fn layout_graph(sizes: &[(f64, f64)], edges: &[(usize, usize)]) -> Vec<(f64, f64)> {
    let n = sizes.len();
    let mut pos = vec![(0.0_f64, 0.0_f64); n];
    if n == 0 {
        return pos;
    }

    let mut adj: Vec<Vec<usize>> = vec![Vec::new(); n];
    for &(a, b) in edges {
        adj[a].push(b);
        adj[b].push(a);
    }

    let mut seen = vec![false; n];
    let mut comps: Vec<Vec<usize>> = Vec::new();
    for start in 0..n {
        if seen[start] {
            continue;
        }
        seen[start] = true;
        let mut stack = vec![start];
        let mut comp = Vec::new();
        while let Some(cur) = stack.pop() {
            comp.push(cur);
            for &next in &adj[cur] {
                if !seen[next] {
                    seen[next] = true;
                    stack.push(next);
                }
            }
        }
        comp.sort();
        comps.push(comp);
    }

    //Lay each component out in its own local coordinate space, anchored at (0,0)
    let mut boxes: Vec<(f64, f64, Vec<(f64, f64)>)> = Vec::with_capacity(comps.len());
    for comp in &comps {
        let mut local: Vec<usize> = vec![usize::MAX; n];
        for (li, &gi) in comp.iter().enumerate() {
            local[gi] = li;
        }
        let sub_sizes: Vec<(f64, f64)> = comp.iter().map(|&gi| sizes[gi]).collect();
        let sub_edges: Vec<(usize, usize)> = edges
            .iter()
            .filter(|(a, _)| local[*a] != usize::MAX)
            .map(|&(a, b)| (local[a], local[b]))
            .collect();

        let mut sub = force_layout(&sub_sizes, &sub_edges);
        let mut min_x = sub[0].0 - sub_sizes[0].0 * 0.5;
        let mut min_y = sub[0].1 - sub_sizes[0].1 * 0.5;
        let mut max_x = sub[0].0 + sub_sizes[0].0 * 0.5;
        let mut max_y = sub[0].1 + sub_sizes[0].1 * 0.5;
        for i in 1..sub.len() {
            min_x = min_x.min(sub[i].0 - sub_sizes[i].0 * 0.5);
            min_y = min_y.min(sub[i].1 - sub_sizes[i].1 * 0.5);
            max_x = max_x.max(sub[i].0 + sub_sizes[i].0 * 0.5);
            max_y = max_y.max(sub[i].1 + sub_sizes[i].1 * 0.5);
        }
        for p in sub.iter_mut() {
            p.0 -= min_x;
            p.1 -= min_y;
        }
        boxes.push((max_x - min_x, max_y - min_y, sub));
    }

    let gap = 34.0;
    let mut order: Vec<usize> = (0..comps.len()).collect();
    order.sort_by(|&a, &b| {
        boxes[b]
            .1
            .partial_cmp(&boxes[a].1)
            .unwrap_or(std::cmp::Ordering::Equal)
            .then(comps[b].len().cmp(&comps[a].len()))
            .then(a.cmp(&b))
    });

    let area: f64 = boxes.iter().map(|b| (b.0 + gap) * (b.1 + gap)).sum();
    let widest = boxes.iter().map(|b| b.0).fold(0.0_f64, f64::max);
    let shelf_w = (area * 1.9).sqrt().max(widest);

    let (mut x, mut y, mut row_h) = (0.0_f64, 0.0_f64, 0.0_f64);
    for &ci in &order {
        let (w, h, ref sub) = boxes[ci];
        if x > 0.0 && x + w > shelf_w {
            x = 0.0;
            y += row_h + gap;
            row_h = 0.0;
        }
        for (li, &gi) in comps[ci].iter().enumerate() {
            pos[gi] = (sub[li].0 + x, sub[li].1 + y);
        }
        x += w + gap;
        row_h = row_h.max(h);
    }

    pos
}

struct Panel {
    graph: String,
    graph_w: f64,
    legend: Vec<(String, String, usize)>,
    height: f64,
}

fn render_panel(graph: &FunctionGraph) -> Panel {
    let n = graph.nodes.len();

    let sizes: Vec<(f64, f64)> = graph
        .nodes
        .iter()
        .map(|node| {
            let label_w = node.label.chars().count() as f64 * CHAR_W;
            let detail_w = match &node.detail {
                Some(detail) => detail.chars().count() as f64 * DETAIL_SIZE * 0.6,
                None => 0.0,
            };
            let w = (label_w.max(detail_w) + 16.0).max(30.0);
            let h = if node.detail.is_some() {
                NODE_H + DETAIL_H
            } else {
                NODE_H
            };
            (w, h)
        })
        .collect();

    let mut pos = layout_graph(&sizes, &graph.edges);

    //Shift the whole cloud so its bounding box starts at the panel's drawing origin
    let mut min_x = 0.0_f64;
    let mut min_y = 0.0_f64;
    let mut max_x = 0.0_f64;
    let mut max_y = 0.0_f64;
    for i in 0..n {
        if i == 0 {
            min_x = pos[i].0 - sizes[i].0 * 0.5;
            min_y = pos[i].1 - sizes[i].1 * 0.5;
            max_x = pos[i].0 + sizes[i].0 * 0.5;
            max_y = pos[i].1 + sizes[i].1 * 0.5;
            continue;
        }
        min_x = min_x.min(pos[i].0 - sizes[i].0 * 0.5);
        min_y = min_y.min(pos[i].1 - sizes[i].1 * 0.5);
        max_x = max_x.max(pos[i].0 + sizes[i].0 * 0.5);
        max_y = max_y.max(pos[i].1 + sizes[i].1 * 0.5);
    }
    for p in pos.iter_mut() {
        p.0 += PAD - min_x;
        p.1 += PAD + TITLE_H - min_y;
    }

    let graph_w = (max_x - min_x) + PAD * 2.0;
    let graph_h = (max_y - min_y) + PAD * 2.0 + TITLE_H;

    let mut svg = String::new();

    svg.push_str(&format!(
        "<text x=\"{:.1}\" y=\"24\" font-size=\"14\" font-family=\"{}\" font-weight=\"bold\" fill=\"#111111\">{}</text>\n",
        PAD / 2.0,
        FONT,
        escape_xml_text(&graph.name)
    ));
    svg.push_str(&format!(
        "<text x=\"{:.1}\" y=\"24\" font-size=\"11\" font-family=\"{}\" fill=\"#7a7a85\">{} nodes, {} interferences</text>\n",
        PAD / 2.0 + graph.name.chars().count() as f64 * 8.6 + 12.0,
        FONT,
        n,
        graph.edges.len()
    ));

    //Dense interference graphs turn into a solid mat of lines, so fade them as the count climbs
    let edge_alpha = (28.0 / (graph.edges.len().max(1) as f64)).clamp(0.10, 0.42);
    for &(a, b) in &graph.edges {
        svg.push_str(&format!(
            "<line x1=\"{:.1}\" y1=\"{:.1}\" x2=\"{:.1}\" y2=\"{:.1}\" stroke=\"#5a5a66\" stroke-width=\"1\" stroke-opacity=\"{:.2}\"/>\n",
            pos[a].0, pos[a].1, pos[b].0, pos[b].1, edge_alpha
        ));
    }

    for (i, node) in graph.nodes.iter().enumerate() {
        let (w, h) = sizes[i];
        svg.push_str(&format!(
            "<rect x=\"{:.1}\" y=\"{:.1}\" width=\"{:.1}\" height=\"{:.1}\" rx=\"{:.1}\" fill=\"{}\" stroke=\"{}\" stroke-width=\"1\"/>\n",
            pos[i].0 - w * 0.5,
            pos[i].1 - h * 0.5,
            w,
            h,
            (h * 0.5).min(10.5),
            fill_of(&node.slot),
            stroke_of(&node.slot)
        ));

        //A temp carries the instruction that defined it on a second line, a var just gets its name
        let label_y = match &node.detail {
            Some(_) => pos[i].1 - DETAIL_H * 0.5,
            None => pos[i].1,
        };
        svg.push_str(&format!(
            "<text x=\"{:.1}\" y=\"{:.1}\" font-size=\"{}\" font-family=\"{}\" text-anchor=\"middle\" dominant-baseline=\"central\" fill=\"{}\">{}</text>\n",
            pos[i].0,
            label_y,
            LABEL_SIZE,
            FONT,
            ink_of(&node.slot),
            escape_xml_text(&node.label)
        ));
        if let Some(detail) = &node.detail {
            svg.push_str(&format!(
                "<text x=\"{:.1}\" y=\"{:.1}\" font-size=\"{}\" font-family=\"{}\" text-anchor=\"middle\" dominant-baseline=\"central\" fill=\"{}\" fill-opacity=\"0.75\">{}</text>\n",
                pos[i].0,
                pos[i].1 + NODE_H * 0.5 - 2.0,
                DETAIL_SIZE,
                FONT,
                ink_of(&node.slot),
                escape_xml_text(detail)
            ));
        }
    }

    //One legend row per distinct location this function actually used
    let mut rows: BTreeMap<(u8, u8, u8, u8), (String, String, usize)> = BTreeMap::new();
    for node in &graph.nodes {
        let entry = rows
            .entry(legend_key(&node.slot))
            .or_insert((legend_text(&node.slot), fill_of(&node.slot), 0));
        entry.2 += 1;
    }
    let legend: Vec<(String, String, usize)> = rows.into_values().collect();
    let legend_h = TITLE_H + 26.0 + legend.len() as f64 * LEGEND_ROW + PAD;

    Panel {
        graph: svg,
        graph_w,
        height: graph_h.max(legend_h),
        legend,
    }
}

fn render_legend(panel: &Panel, x: f64) -> String {
    let mut svg = String::new();
    svg.push_str(&format!(
        "<text x=\"{:.1}\" y=\"24\" font-size=\"12\" font-family=\"{}\" font-weight=\"bold\" fill=\"#111111\">Registers</text>\n",
        x, FONT
    ));

    let mut y = TITLE_H + 14.0;
    for (name, fill, count) in &panel.legend {
        svg.push_str(&format!(
            "<rect x=\"{:.1}\" y=\"{:.1}\" width=\"14\" height=\"14\" rx=\"3\" fill=\"{}\" stroke=\"#4a4a52\" stroke-width=\"0.7\"/>\n",
            x,
            y - 10.0,
            fill
        ));
        svg.push_str(&format!(
            "<text x=\"{:.1}\" y=\"{:.1}\" font-size=\"10.5\" font-family=\"{}\" fill=\"#111111\">{}</text>\n",
            x + 22.0,
            y,
            FONT,
            escape_xml_text(name)
        ));
        svg.push_str(&format!(
            "<text x=\"{:.1}\" y=\"{:.1}\" font-size=\"9\" font-family=\"{}\" text-anchor=\"end\" fill=\"#84848f\">x{}</text>\n",
            x + LEGEND_W - 40.0,
            y,
            FONT,
            count
        ));
        y += LEGEND_ROW;
    }
    svg
}

pub fn render_svg(graphs: &[FunctionGraph], out_path: &str) {
    if graphs.is_empty() {
        return;
    }

    let panels: Vec<Panel> = graphs.iter().map(render_panel).collect();
    //Every legend sits in the same column, no matter how wide its own graph came out
    let column = panels.iter().map(|p| p.graph_w).fold(0.0_f64, f64::max);
    let total_width = column + LEGEND_W;
    let total_height: f64 = panels.iter().map(|p| p.height).sum();

    let mut svg = String::new();
    svg.push_str(&format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><svg width=\"{:.0}\" height=\"{:.0}\" viewBox=\"0 0 {:.0} {:.0}\" xmlns=\"http://www.w3.org/2000/svg\"><rect width=\"100%\" height=\"100%\" fill=\"white\"/>\n",
        total_width, total_height, total_width, total_height
    ));

    let mut y_offset = 0.0_f64;
    for panel in &panels {
        svg.push_str(&format!("<g transform=\"translate(0,{:.1})\">\n", y_offset));
        svg.push_str(&format!(
            "<rect x=\"{:.1}\" y=\"0\" width=\"{:.1}\" height=\"{:.1}\" fill=\"#fafafb\"/>\n",
            column, LEGEND_W, panel.height
        ));
        svg.push_str(&format!(
            "<line x1=\"{:.1}\" y1=\"14\" x2=\"{:.1}\" y2=\"{:.1}\" stroke=\"#e2e2e6\" stroke-width=\"1\"/>\n",
            column,
            column,
            panel.height - 14.0
        ));
        svg.push_str(&panel.graph);
        svg.push_str(&render_legend(panel, column + 18.0));
        svg.push_str("</g>\n");

        y_offset += panel.height;
        svg.push_str(&format!(
            "<line x1=\"0\" y1=\"{:.1}\" x2=\"{:.0}\" y2=\"{:.1}\" stroke=\"#d8d8de\" stroke-width=\"1\"/>\n",
            y_offset, total_width, y_offset
        ));
    }

    svg.push_str("</svg>\n");

    let _ = std::fs::write(out_path, svg);
}
